blades/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/display', 'UserController@index')->name('Users');
Route::Resource('/movie','AblumController');

//Route::get('/insertform', 'UserController@create');
//Route::get('/movieinsert', 'AblumController@create');

blades/app/Album.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Album extends Model
{
    protected $fillable = [
        'title', 'coverimage','published_date'
    ];
}

blades/app/Artist.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Artist extends Model
{
    //
}

blades/app/Track.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Track extends Model
{
    //
}

blades/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

blades/app/Http/Controllers/AblumController.php
<?php

namespace App\Http\Controllers;

use App\Album;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;

class AblumController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $movie=Album::all();
        return view('displaymovie',['movie'=> $movie]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('movieinsertform',['movie'=>Album::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'bail|required|max:255',
            'coverimage' => 'required',
            'published_date' => 'required|date|after:3/25/2020',
            'gender'=>'required',
            'phone'=>'numeric|digits:10'
        ]);

        Album::create($request->all());
//        $validated = $request->validated();
        return redirect()->route('movie.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id,Request $request)
    {
        Album::create($request->all());
        return redirect()->route('movie.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id,Album $a)
    {
        return view('movieupdateform',['movie'=>$a]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Album $a, $id)
    {

        $a->update($request->all());
        return redirect()->route('movie.index');

        $a->update($request->all());
        return redirect()->route('movie.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $aa=Album::find($id);
        $aa->delete();
        return redirect()->route('movie.index');
    }
}

blades/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

blades/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

blades/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
//        $u= User::all();
//        dd($u);
        return view('display',['u' => User::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('insertform');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

blades/resources/views/display.blade.php
@extends('home')
@section('content')
    <div class="container">
    <td>
        <form action="/movie/insertform">
            <input type="submit" value="Create"></form></td>
        <table border=solid 1px >
            <tr>
                <th>id</th>
                <th>Name</th>
                <th>Email</th>

                <th>Update</th>
                <th>delete</th>
            </tr>
            @foreach($u as $u)
            <tr>
        {{--         {{$u->id}}--}}
                <td>{{$u->id}}</td>
                <td>{{$u->name}}</td>
                <td>{{$u->email}}</td>
                <td>
                    <form action="/user/{{$u->id}}/edit">
                        <input type="submit" value="Update">
                    </form>
                </td>
                <td>
                    <form action="/user/{{$u->id}}" method="post">
                        <input type="hidden" name="_token" value=" csrf_token() " >
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="submit" value="Delete">
                        </form>
                </td>
                </tr>
        @endforeach
        {{--    //    <tr><th>id<th><td>Name</td>Email<td>Password</td><td><a href="/user/{{$u->id}}"></td><td></td></tr>--}}
            </table>
    </div>
    @endsection

blades/resources/views/displaymovie.blade.php
@extends('home')
@section('content')
    <div class="container">
        <td>
            <form action="/movie/create">
                <input type="submit" value="Create"></form></td>
        <table border=solid 1px >
            <tr>
                <th>id</th>
                <th>Title</th>
                <th>CoverImage</th>
                <th>Published Date</th>

                <th>Update</th>
                <th>delete</th>
            </tr>
            @foreach($movie as $u)
                <tr>
                    {{--         {{$u->id}}--}}
                    <td>{{$u->id}}</td>
                    <td>{{$u->title}}</td>
                    <td>{{$u->coverimage}}</td>
                    <td>{{$u->published_date}}</td>
                    <td>
                        <form action="/movie/{{$u->id}}/edit">
                            <input type="submit" value="Update">
                        </form>
                    </td>
                    <td>
                        <form action="movie/{{$u->id}}" method="post">
                            <input type="hidden" name="_token" value="{{csrf_token()}}" >
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="submit" value="Delete">
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>
@endsection

blades/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    You are logged in!
                        <p><a href="display/">Display</a></p>
                        <p><a href="movie/moviedisplay/">Show Movie</a></p>
                        <p><a href="insertform/">Insert</a></p>
                        <p><a href="movieinsert/">Movie Insert</a></p>
                        @yield('content')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

blades/resources/views/insertform.blade.php
@extends('home')
@section('content')
    <form action="/movie/{{$movie->id}}" method="POST">
        <input type="hidden" name="_token" value="csrf_token()" >
        <div><br>Title:<input type="text" name="title"></div>
        <div><br>CoverImage:<input type="text" name="coverimage"></div>
        <div><br>Released Date:<input type="date" name="published_date"></div>
        <br><input type="submit">
    </form>
@endsection

blades/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

blades/resources/views/movieinsertform.blade.php
@extends('home')
@section('content')
    <form action="{{route('movie.store')}}" method="POST">
        <input type="hidden" name="_token"  value="{{csrf_token()}}">
        <div><br>Title:<input type="text" name="title">@error('title')
            <span class="alert text-alert">{{ $message }}</span>
            @enderror</div>

        <div><br>CoverImage:<input type="text" name="coverimage">@error('coverimage')
            <span class="alert text-alert">{{ $message }}</span>
            @enderror</div>
        <div>
            <br>Released Date:<input type="date" class="@error('published_data')is-invalid @enderror" name="published_date">
            @error('published_date')
            <span class="alert text-alert">{{ $message }}</span>
            @enderror
        </div>
        <div>
            <br>Number:<input type="tel" class="@error('phone')is-invalid @enderror" name="phone">
            @error('phone')
            <span class="alert text-alert">{{ $message }}</span>
            @enderror
        </div>
        <div>
            <br>GENDER:<br><input type="radio" name="gender" class="@error('gender')is-invalid @enderror" value="male"> Male<br>
            <input type="radio" name="gender" class="@error('gender')is-invalid @enderror" value="female"> Female<br>
{{--            <input type="RADIO" class="@error('gender')is-invalid @enderror" name="gender">--}}
            @error('gender')
            <span class="alert text-alert">{{ $message }}</span>
            @enderror
        </div>
        <br><input type="submit">
    </form>
{{--    @if ($errors->any())--}}
{{--        <div class="alert alert-danger">--}}
{{--            <ul>--}}
{{--                @foreach ($errors->all() as $error)--}}
{{--                    <li>{{ $error }}</li>--}}
{{--                @endforeach--}}
{{--            </ul>--}}
{{--        </div>--}}
{{--    @endif--}}

@endsection

blades/resources/views/movieupdateform.blade.php
@extends('home')
@section('content')
    <form action="{{route('movie.update')}}" method="POST">
        <input type="hidden" name="_token" value="{{csrf_token()}}" >
        <div><br>Title:<input type="text" name="title"></div>
        <div><br>CoverImage:<input type="text" name="coverimage"></div>
        <div><br>Released Date:<input type="date" name="published_date"></div>
        <br><input type="submit">
    </form>
@endsection